import type { Metadata } from "next";
import { ReactNode } from "react";
import { cn } from "@/app/_common/utils";

import "./globals.css";

import { tacticSans } from "@/app/_common/utils";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(tacticSans.variable)}>{children}</body>
    </html>
  );
}
